name: Terraform Test

on:
  workflow_call:
    inputs:
        scan-ref:
            required: true
            type: string
        trivy-tfvars:
          required: false
          type: string
          default: ''
          description: 'Optional path to tfvars file for Trivy scanning'

jobs:
  trivy:
    name: Trivy Scan
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
    
        - name: Run Trivy on Terraform Code
          uses: aquasecurity/trivy-action@0.29.0
          with:
            scan-type: config
            scan-ref: ${{ inputs.scan-ref }}
            exit-code: 1
            tf-vars: ${{ inputs.trivy-tfvars != '' && inputs.trivy-tfvars || '' }}
            version: v0.67.0