name: Terraform Test

on:
  workflow_call:
    inputs:
        scan-ref:
            required: true
            type: string

jobs:
  trivy:
    name: Trivy Scan
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
    
        - name: Run Trivy on Terraform Code
          uses: aquasecurity/trivy-action@0.28.0
          with:
            scan-type: config
            scan-ref: ${{ inputs.scan-ref }}
            exit-code: 1